name: Build NIF Preview Plugin

on:
  push:
    branches: main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Build NIF Preview Plugin
        uses: ModOrganizer2/build-with-mob-action@master
        with:
          mo2-third-parties: libbsarch
          mo2-dependencies: cmake_common
